# Logger configuration
pattern = "%+"
level = "info"
default_sink = "default"

[[sink]]
    name = "default"
    [[sink.output]]
        type = "null"
    [[sink.output]]
        type = "stdout"
    [[sink.output]]
        type = "stderr"
[[sink]]
    name = "file"
    [[sink.output]]
        type = "file"
        path = "logs/file"
    [[sink.output]]
        type = "rotating-file"
        path = "logs/rotate"
        extension = "log"
        max_size = "1024M"
        keep = 3
    [[sink.output]]
        type = "daily-file"
        path = "logs/daily"
        extension = "log"
        refresh_on = "12:00"

[[channel]]
    name = "global"
    level = "info"
    sink = "default"

[[channel]]
    name = "var"
    level = "debug"
    sink = "file"
